version: '3'
services:
  acapy:
    image: bcgovimages/aries-cloudagent:py36-1.16-1_0.7.4-rc1
    depends_on:
      - db
    ports:
      - "${ACAPY_ADMIN_PORT}:${ACAPY_ADMIN_PORT}"
      - "${ACAPY_ENDPOINT_PORT}:${ACAPY_ENDPOINT_PORT}"
    environment:
      WAIT_HOSTS: "db:5432"
      WAIT_HOSTS_TIMEOUT: "300"
      WAIT_SLEEP_INTERVAL: "5"
      WAIT_HOST_CONNECT_TIMEOUT: "3"
    entrypoint: /bin/bash
    command: [
       "-c",
       "curl -d '{\"seed\":\"${AGENT_WALLET_SEED}\", \"role\":\"TRUST_ANCHOR\", \"alias\":\"${LABEL}\"}' -X POST ${LEDGER_URL}/register; \
        sleep 5; \
        /wait; \
        aca-py start \
        --auto-provision \
        -it http '0.0.0.0' ${ACAPY_ENDPOINT_PORT} \
        -ot http \
        --admin '0.0.0.0' ${ACAPY_ADMIN_PORT} \
        -e ${ACAPY_ENDPOINT_URL} \
        --wallet-type indy \
        --wallet-name ${WALLET_NAME}
        --wallet-key ${WALLET_KEY}
        --wallet-storage-type postgres_storage
        --wallet-storage-config '{\"url\":\"db:5432\",\"max_connections\":5}'
        --wallet-storage-creds '{\"account\":\"${POSTGRES_USER}\",\"password\":\"${POSTGRES_PASSWORD}\",\"admin_account\":\"${POSTGRES_USER}\",\"admin_password\":\"${POSTGRES_PASSWORD}\"}'
        --seed ${AGENT_WALLET_SEED} \
        --genesis-url ${LEDGER_URL} \
        --tails-server-base-url ${TAILS_SERVER_URL} \
        --label ${LABEL} \
        --auto-accept-invites \
        --auto-accept-requests \
        --admin-insecure-mode \
        --auto-store-credential \
        --accept-taa service_agreement 2.0 \
        --auto-ping-connection \
        --log-level info",
    ]

  db:
    image: postgres:latest
    hostname: db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./postgres:/docker-entrypoint-initdb.d/
      - ./.postgres:/var/lib/postgresql
    ports:
      - "5432:5432"

  tails-server:
    image: ldej/tails-server:latest
    ports:
      - 6543:6543
    volumes:
      - ./tails/tails-files:/tails-files/
    environment:
      GENESIS_URL: "${LEDGER_URL}"
      TAILS_SERVER_URL: "${TAILS_SERVER_URL}"
    command: >
      tails-server
        --host 0.0.0.0
        --port 6543
        --storage-path /tails-files
        --log-level INFO      
